### ISSUE TITLE
Take Notes new note filename creation ignores $word$

### ISSUE THREAD

**Issue by rob040** [francostellari/NppPlugins#34] opened 2022-11-04 10:40 UTC
Take Notes new note filename creation ignores `$word$` in Note name, i.e. it is always empty, while the Options dialog 'Expand' button shows expected result.

I also noted that (some?) option settings do not take effect until restarting npp. So I did restart npp but found that the selected word is never used in new note file names.

This feature used to work on other computer which I no longer have, and found this handy extension handy to organize different kinds of notes.

I have configured in Options:
Folder: `%USERPROFILE%\Documents\Notes`
Note name: `note_$word$_$date$_$time$`
Note extension: `.txt`

Running Notepad++ v8.4.6 (32-bit) on Windows 10 64-bit

**Comment by rob040** [comment] 2022-11-04 11:05
I noticed that the "Save as note" toolbar button (not enabled by default) does create the note file in the configured directory and filename where the selected text is expanded in the `$word$` place holder.

This is for me a good and workable workaround to above stated issue.

**Comment by aavramch** [comment] 2022-11-12 23:50
Same issue, new notes are created as 'new 1~'

**Comment by francostellari** [comment] 2022-12-27 00:35
Hi, sorry for the late response.
Your initial issue will be fixed in the next release. New will work as SaveAs
I cannot reproduce your latest issue of "new1~" but there is a chance that it will be fixed as well.

**Closed** 2023-02-19 14:30 UTC
